---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAz17kv5G1Xnkdx3xhajYVYB0RtxbC83D2Uhfl2zwYhW8wHAEvWitUtgUi1UV/EBwpyBA1pbWfdMJjJHRZyMQPCYL/9aS1W8WchrZWakanAJ+wNEdwrqdf1iciNtrl9a0X91CeFQ/OHv1Hjv8vXMAFU5ZEiHqniWMmOsJFY89N9Dk0QRAS4Ot887KfaOXM/6ltUxhVtPYcxI0pPV2OU1ifgr3tUxj85kerTr4XM4QZwNEThszidMdr1wODaYosoFQG+SGegzbsyMCxapZ8IzoDwCyp6yJt7pRIcpxRjtmBWxuDRynKVFVlUShzcSyEWZYmDIRoO0p+airzNqvO/Rs1VbGYuWXwWLGxYfycw5kVamXyhfsPWeWn/lnEda1awou9eShFsSULYBX9ASj2bg7EAwo+5A4mn8LQMAeVhu+IPn42neOQBVgVsfBokDq5oagghoIcVzjOsfciYeNAYf2SX/1hWLB6biPNKg89DSTY6GTzyGimjZ1dE2c3831EQq6L4CR/cV9KRz0a4IzdKV8JLCBuPEez42BioNSDA7tQdgwSGSLd7ZGioVxEqLoX5UX1VGaaZJ8PpyKzhrtelKOZa4hoaqNCZ7pJn29bI1IBPJGVkxicMDw7FmoAxC8ztL5IeI/9bFSTqPLUH4rZpw1s1kRisBNJL2LNud0qRTotyLlj1nomsfFEdC4+iMVczk47sygtgduECgiKPVg==
    STRIPE_API_KEY: AgDGz0LrDbPaKILZHbGbNnUPxZnZ7EmgJC8hYe1LID/Qk1c+4Q3oYRenmPViYn9YVjpYWw5RGR/73FWk4Ecze09TQc7OhLcAexwwSPlTr681aNR9Y3WFYUnaDJboAWYU0AhR2EpUHw2a8tYQyWCgetF+6byrxdtMsiPnA2VF16rWmNdBA3VdS/HOWlrXGqkLgU6mGkyOZiNfmF22vHgsruYEu/X0RMkgzXDvC5dbN0wLxqoZso3OaaOLzbGZQZJ96F7iXgqibwXPaJLofI1/dfokMy9KS3zsOmOb6hS4oIrNDLSHkEMzYAHkQw7kil1Jue8vrnoxOWfWoTxgqtoMNGdGZ3zum5nFOnzWO16Be6h47EppTwEo87jdmZkVwzRJuFMU8Xud88h9gm7sTzfxPlYW5Lxyrj1NstPe6RbrumCsB46ykz+c9ro6lUvfCD+aEjslIWts9HOiIsJppnjmooVbKV7HubIjEK+AaakHbT353X4CidJXcwHOpVE+HKfWX6mAAFmLl2QANbNXOYUhSvpKCa2hJs7aLZhdkPipKfqYZKrsxa7ZY99Sr1lrzjxCR7qD/inWP6PLznaVAUN84v7Z2a93LPU1xHVGc1DhZRdXGYmm8ETGd0bWytMFUb3L2u0XDeNFCMVkhJ+6qt0zQTnyXP0GIfjGyuE69RTYotWGUE2sMXJJTFVUkU5llVqyHmT+csfQNynXCKi+tZH2SUcoperJDGrUYrgVellOuw==
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
